title: "Future Electric Studios"
description: "Future Electric Studios — non-profit, multi-platform Roblox community and creative projects."
baseurl: ""        # leave empty for user/organization pages
url: "https://futureelectricstudios.github.io"
theme: minima
markdown: kramdown
plugins:
  - jekyll-seo-tag
